project_id = "flafgqrxmrtfibydeuog"

[functions.create-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.migrate-regional]
verify_jwt = false